name: Unit tests

on: [push, pull_request]

jobs:
  # ============================
  # Backend unit tests (Node.js)
  # ============================
  backend-unit-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: nodejs-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: nodejs-backend/package-lock.json

      - name: Install backend dependencies
        run: npm ci
        env:
          CI: true

      - name: Run backend unit tests
        run: npm test -- --ci --passWithNoTests
        env:
          CI: true

  # =====================================
  # Frontend unit tests 
  # =====================================
  frontend-unit-tests:
    # run if package.json exist in root
    if: hashFiles('package.json') != ''
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install frontend dependencies
        run: npm ci
        env:
          CI: true

      - name: Run frontend unit tests
        run: npm run test -- --ci --passWithNoTests
        env:
          CI: true
